CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, role text NOT NULL, UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read own role" ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid());
INSERT INTO public.user_roles(user_id,role) SELECT id,'owner' FROM auth.users WHERE id='34023a47-0810-447b-92e7-7b1f1296f424';
CREATE OR REPLACE FUNCTION public.is_arha_owner() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=auth.uid() AND role='owner') $$;
REVOKE ALL ON FUNCTION public.is_arha_owner() FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.is_arha_owner() TO authenticated;
CREATE OR REPLACE FUNCTION public.owns_shop(_shop_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT public.is_arha_owner() AND EXISTS(SELECT 1 FROM public.shops WHERE id=_shop_id AND id='57fddf6b-ac15-4803-946e-c61b72519a64' AND owner_id=auth.uid()) $$;
REVOKE ALL ON FUNCTION public.owns_shop(uuid) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.owns_shop(uuid) TO authenticated;
CREATE POLICY "Arha only public store" ON public.shops AS RESTRICTIVE FOR SELECT TO anon,authenticated USING(id='57fddf6b-ac15-4803-946e-c61b72519a64');
CREATE POLICY "Arha owner update" ON public.shops AS RESTRICTIVE FOR UPDATE TO authenticated USING(public.owns_shop(id)) WITH CHECK(public.owns_shop(id));
CREATE POLICY "no new merchant shops" ON public.shops AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK(false);
CREATE POLICY "preserve single store" ON public.shops AS RESTRICTIVE FOR DELETE TO authenticated USING(false);
CREATE POLICY "Arha only catalogue" ON public.products AS RESTRICTIVE FOR SELECT TO anon,authenticated USING(shop_id='57fddf6b-ac15-4803-946e-c61b72519a64');
CREATE POLICY "Arha media upload" ON storage.objects AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK(bucket_id<>'boutique-medias' OR public.is_arha_owner());
CREATE POLICY "Arha media update" ON storage.objects AS RESTRICTIVE FOR UPDATE TO authenticated USING(bucket_id<>'boutique-medias' OR public.is_arha_owner()) WITH CHECK(bucket_id<>'boutique-medias' OR public.is_arha_owner());
CREATE POLICY "Arha media delete" ON storage.objects AS RESTRICTIVE FOR DELETE TO authenticated USING(bucket_id<>'boutique-medias' OR public.is_arha_owner());